.RECIPEPREFIX = >
current_file = 20.4.c
commons = ../lib/error_functions.c ../lib/get_num.c signal_functions.c

current : $(current_file) $(commons)
> gcc -g -o current $(current_file) $(commons) $(CFLAG_ARGS)

clean: 
> rm -f current a.out