#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include "../lib/error_functions.h"

int main(int argc, char* argv[]) {
  if (argc != 2) {
    usageErr("%s <input_file>", argv[0]);
  }

  char* inp_file_name = argv[1];
  int src_fd = open(inp_file_name, O_RDWR);
  if (src_fd == -1) {
    errExit("errpr opening source file");
  }

  printf("system page size is: %ld\n", sysconf(_SC_PAGE_SIZE));
  struct stat buf;
  if (fstat(src_fd, &buf) == -1) {
    errExit("error finding file stat");
  }

  printf("file size is: %ld\n", buf.st_size);

  // create a larger mmap
  // file size is 9360bytes,
  // generated by: dd if=/dev/random of=rand_inp count=120
  char* addr = mmap(NULL, 2 * buf.st_size, PROT_READ, MAP_PRIVATE, src_fd, 0);
  if (addr == MAP_FAILED) {
    errExit("mapping failed");
  }

  // SIGBUS
  //  printf("value at point in unmapped file region: %c", addr[13000]);

  // SIGSEGV
  // this doesn't happen, probably because we're accessing process memory still
  // which is not inaccessible
  printf("value at point in unmapped file region: %c", addr[40000]);
}