.RECIPEPREFIX = >
current_file = c5/dup.c
commons = lib/error_functions.c lib/get_num.c

current : $(current_file) $(commons)
> gcc -g -o current $(current_file) $(commons)

clean: 
> rm -f current a.out